### ISSUE TITLE
How does your "Update Wordinfo" workflow work?

### ISSUE THREAD

**Issue by Xeros08** [Ludeon/RimWorld-de#73]
At the Spanish translation we've been looking for a way to automate the process of extracting the words that then go into the [WordInfo/Gender](https://github.com/Ludeon/RimWorld-de/tree/master/Core/WordInfo/Gender) folders.

I've realised that you have automated this with the  [update-wordinfo.yml](https://github.com/Ludeon/RimWorld-de/blob/master/.github/workflows/update-wordinfo.yml) github workflow.

Can we use your workflow to accelerate the procces?

**Comment by Ragnar-F** [comment]
> Can we use your workflow to accelerate the procces?

Everyone is free to use and modify this workflow.

> How does your "Update Wordinfo" workflow work?

This workflow is triggered every time a commit is pushed in the master branch. When triggered, it scans XML files located in specific folders for specific tag elements. For the current list of folders being scanned, see the code under `$paths`. For the current list of tag elements being parsed to get the words, see the code under `# unknown gender`, `# male gender` and `# female gender`. New words that cannot be clearly assigned a gender are stored in Core/WordInfo/Gender/new_words.txt and must be manually sorted into either Female.txt, Male.txt or Neuter.txt. The words are automatically converted to lowercase and sorted alphabetically within their list.

To make update-wordinfo.yml work, add it to the .github/workflows/ folder. Additionally, I recommend creating empty files named Female.txt, Male.txt, Neuter.txt and Plural.txt in the folder Core/WordInfo/Gender/ beforehand, otherwise you may get an error message.

Note that Plural.txt actually has no function. It rather serves as a storage place for words that are neither feminine, masculine nor neutral. In German language this would be for example plural words.

If you're unsure about this, you can test it beforehand in your own private GitHub repository. That's how I did it, too.

**Comment by Xeros08** [comment]
Thankyou ^^

**Comment by Xeros08** [comment]
I've run this workflow on our Repository, and I had already created the `Male.txt`, `Female.txt`, `Neuter.txt` & `Plural.txt` files

**Comment by Xeros08** [comment]
![imagen_2021-04-10_220513](https://user-images.githubusercontent.com/42175313/114283199-d2ce7280-9a48-11eb-8e4a-c1c88e9d4c7a.png)
In this screenshot you can see the error that it thows.

**Comment by Ragnar-F** [comment]
new_words.txt must also always be present; that is, it should not be deleted.

**Comment by Xeros08** [comment]
Ok, lets see if now this works...
Ty for your time ^^

**Comment by Xeros08** [comment]
Nope, it keeps on throwing the same error.

**Comment by Xeros08** [comment]
Yeah, that was it. Now it works.
I just filled all the documents with a dor ".", and it just worked.
Weird, but I no longer care.

Anyway, thanks!

**Comment by Ragnar-F** [comment]
I will have a closer look soon, what exactly is the problem here. Thanks for trying it out.

**Comment by Ragnar-F** [comment]
7268621 improves update-wordinfo.yml. Specifically:
- Missing files/folders are created automatically
- Text files can be completely empty
- Action can be started manually
